[build]
  command = "# no build needed"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# [[plugins]]
# package = "@netlify/plugin-scheduled-functions"

[functions.start-scheduler]
  schedule = "*/5 * * * *"
